# Generated by Django 4.0.3 on 2022-05-08 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_packagedaysdetails_package_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='packages',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=550)),
                ('phoneOne', models.IntegerField(null=True)),
                ('phoneTwo', models.IntegerField(null=True)),
                ('date', models.CharField(max_length=25, null=True)),
                ('peopleNumber', models.IntegerField(null=True)),
                ('otherInfo', models.CharField(max_length=1500, null=True)),
                ('status', models.CharField(max_length=25, null=True)),
                ('package_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.packages')),
            ],
        ),
    ]
