# Generated by Django 4.0.3 on 2022-05-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_packages_discount_alter_packages_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='discount',
        ),
    ]
